name: Lint and Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**.github/workflows/*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint PHP files
        uses: StephaneBour/actions-php-lint@8.2
        with:
         dir: './src'

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
